// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
...ffffffffff...
...f1111111ff...
...ff1111111f...
...f1f111f11f...
...f11f1f111f...
...f111f1111f...
...ffffffffff...
.......f........
.......f........
.......f......f.
ff....ff...ffff.
ff....ff..f...ff
..f..fff.f...fff
..f..ffff....ff.
..f..fff.....f..
...ff.ff....f.ff
......fff...ff..
........f..f....
........f.......
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
.......f........
......f.........
.....f..........
....f...........
...ff...........
...f............
...f............
...f............
....f...........
....f...........
.....ff.........
......f.........
.......f........
.......f........
.......f........
........f.......
........f.......
.........f......
.........f......
........ff......
........f.......
.......ff.......
......ff........
......f.........
......f.........
......f.........
.....fff........
....ff..fff.....
...ff.....f.....
..ff.......ff...
.fff........ff..
f.f..........f..
..f..........f..
.............f..
`;
            case "^i?S5VmQ:,M9!QtWKLkG":
            case "Jeff":return img`
. . . f f f f f f f f f f . . . 
. . . f d d d d d d d d f . . . 
. . . f 1 1 1 d d 1 1 1 f . . . 
. . . f 1 f 1 f f 1 f 1 f . . . 
. . . f 1 1 1 d d 1 1 1 f . . . 
. . . f d d d d d d d d f . . . 
. . . f d d d d d d d d f . . . 
. f f f f f f f f f f f f f f . 
. f 4 f 4 4 4 4 4 4 4 4 f 4 f . 
. f 4 f 4 4 5 5 5 5 4 4 f 4 f . 
. f 4 f 4 5 5 4 4 4 4 4 f 4 f . 
. f 4 f 4 5 5 4 4 5 4 4 f 4 f . 
. f 4 f 4 4 5 5 5 5 4 4 f 4 f . 
. f 4 f 4 4 4 4 4 4 4 4 f 4 f . 
. f f f f f f f f f f f f f f . 
. . . f 4 f . . . . f 4 f . . . 
. . . f 4 f . . . . f 4 f . . . 
. . . f f f . . . . f f f . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
